---
title: "Devoir séance 3"
output:
  html_document:
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


[Retour à la page d'accueil](https://scortijo.github.io/2022_L3_R/)

<br>

Ceci est la partie correspondant à la séance 3 du contrôle continu qui combinera les exercices à faire entre les séances. Pour cela:


- Reprenez le script R `Script_controle_continu1_numéro_étudiant.R` (avec votre votre propre numéro à la place de `numéro_étudiant`) que vous avez sauvé dans le devoir de la séance précédente.

<br>

- Chargez la librairie `ggpubr`

<br>

- Ajoutez au boxplot (qui est à la fin de votre script) le résultat d'un test de comparaison de moyennes entre les deux niveaux d'azote pour chacune des accessions.    
*Aide: pour faciliter la lecture du résultat du test, utiliez `label = "p.signif"` afin de ne faire apparaitre que les étoiles de significativité du test pour chaque accession.*   

Formulez une interprétation à propos de l'effet du la concentration en azote sur le poids des plantes d'Arabidopsis.

<br>

- Avec l'une des fonctions que nous avons vue dans la deuxième partie du cours, selectionnez toutes les colonnes de l'objet `nitrate_data` sauf la colonne `Nlevel`.

<br>

- Avec une autre fonction que nous avons vue dans la deuxième partie du cours, gardez uniquement les lignes de l'objet `nitrate_data` qui sont l'accession `Col-0`.

<br>

- **C'est fini. N'oubliez pas de sauver votre fichier. Le script contenant tous les exercices à faire pour les séances 1, 2 et 3 est la première moitié du contrôle continu et doit être déposé sur Moodle au plus tard le 16/11/2022 à minuit.**

<br>




