---
title: "Devoir_séance1"
output:
  html_document:
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


[Retour à la page d'accueil](https://scortijo.github.io/2022_L3_R/)

Ceci est le début du contrôle continu qui combinera les exercices à faire entre les séances.

**!Attention! Vous devez tout d'abord installer R et R studio en utilisant les instructions sur [la page d'accueil](https://scortijo.github.io/2022_L3_R/)**

<br>

Une fois R et R studio installés, voici la première partie du contrôle continu:

<br>

- Créez un nouveau script R que vous sauvez immediatement sous le nom de `Script_controle_continu1_numéro_étudiant.R` en remplaçant `numéro_étudiant` par votre propre numéro.

<br>

- Chargez le package `tidyverse`(en utilisant `library()`)

<br>

- Définissez votre répertoire de travail dans le dossier `session1_organisations`  (en utilisant `setwd()`)

<br>

- Importez le tableau `Cheng_2021_Arabidopsis_N.txt` en utilisant la bonne fonction et gardez le dans l'objet `nitrate_data`. 

*Aide: le fichier est au format `.txt` avec les colonnes séparées par une tabulation.*

<br>

Vous pouvez trouver plus d'information sur le jeu de données dans cet article de [Cheng et al., 2021](https://www.nature.com/articles/s41467-021-25893-w#MOESM4).
Dans le fichier la colonne `Accession` contient le nom des accessions d'Arabidopsis utilisées. La colonne `Nlevel` indique si les plantes ont été traitées avec une faible ou forte concentration en azote. La concentration exacte d'azote utilisée (en mg) est indiquée dans la colonne `AppliedN_mg`. La colonne `DryWeight_g` indique le poids des plantes séchées à la fin de l'expérience. Trois répliquas ont été effectués pour chaque traitement sur chaque accession

<br>

- **C'est fini. N'oubliez pas de sauver votre fichier que vous réutiliserez pour le reste du contrôle continu.**

<br>




